CREATE DATABASE QLXD;

-- tao bang
CREATE TABLE DOANHNGHIEPNK(
	MADN	char(4) not null,
	TENDN	varchar(40),
	NGAYTL	datetime,
	DIACHI	varchar(40),
	SDT		varchar(20),
	LOAIDN	varchar(20)
);
CREATE TABLE LOAIXANG(
	MALX	char(4) not null,
	TENLX	varchar(40),
	MDBQ	varchar(20)
);
CREATE TABLE XANGDAU(
	MAXD	char(4) not null,
	TENXD	varchar(40),
	MALX	char(4),
	GIACOSO	decimal(5,3),
	THUEPHI		int
);
CREATE TABLE CUAHANG(
	MACH	char(4) not null,
	TENCH	varchar(40),
	BACCL	varchar(2),
	RONGDD	int,
	CAOTB	int,
	CAOMC	int
);
CREATE TABLE NHAVANCHUYEN(
	MANVC	char(4) not null,
	TENNVC	varchar(40),
	SDT		varchar(20),
    DIACHI	varchar(40)
);
CREATE TABLE NHAP(
	MAXD		char(4),
	MACH		char(4),
	NGAYNHAP	datetime,
	SOLUONG		int,
	GIANHAP		decimal(5,3)
);
CREATE TABLE VANCHUYEN(
	MANVC		char(4),
	MAXD		char(4),
	NGAYVC		datetime,
	NOIDI		varchar(40),
	NOIDEN		varchar(40)
);
CREATE TABLE DN_XD(
	MADN		char(4),
	MAXD		char(4),
	NGAYNK		datetime
);

-- khoa chinh
ALTER TABLE DOANHNGHIEPNK ADD PRIMARY KEY (MADN);
ALTER TABLE LOAIXANG ADD PRIMARY KEY (MALX);
ALTER TABLE XANGDAU ADD PRIMARY KEY (MAXD);
ALTER TABLE CUAHANG ADD PRIMARY KEY (MACH);
ALTER TABLE NHAVANCHUYEN ADD PRIMARY KEY (MANVC);
 
-- khoa ngoai
ALTER TABLE XANGDAU ADD CONSTRAINT FK_xdMALX FOREIGN KEY (MALX) REFERENCES LOAIXANG(MALX);

ALTER TABLE NHAP ADD CONSTRAINT FK_nhapMAXD FOREIGN KEY (MAXD) REFERENCES XANGDAU(MAXD);
ALTER TABLE NHAP ADD CONSTRAINT FK_nhapMACH FOREIGN KEY (MACH) REFERENCES CUAHANG(MACH);

ALTER TABLE VANCHUYEN ADD CONSTRAINT FK_vcMANVC FOREIGN KEY (MANVC) REFERENCES NHAVANCHUYEN(MANVC);
ALTER TABLE VANCHUYEN ADD CONSTRAINT FK_vcMAXD FOREIGN KEY (MAXD) REFERENCES XANGDAU(MAXD);

ALTER TABLE DN_XD ADD CONSTRAINT FK_dnxdMADN FOREIGN KEY (MADN) REFERENCES DOANHNGHIEPNK(MADN);
ALTER TABLE DN_XD ADD CONSTRAINT FK_dnxdMAXD FOREIGN KEY (MAXD) REFERENCES XANGDAU(MAXD);

-- rang buoc 




